[workspace]

members = [
    "aegis",
    "core",
    "shared",
]

resolver = "2"

[workspace.dependencies]
clap = {version = "4.5", features = ["derive"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.11"